zeus-file-mgmt:
  api:
    version: 1.0.0
server:
  port: 8082
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/filemgmtdb?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    username: filemgmtapp
    password: password
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        show_sql: true
        format_sql: true
  flyway:
    user: filemgmtadmin
    password: password
  profiles:
    active: local, clean
logging:
  file:
    name: logs/local/filemgmt.log
  level:
    org:
      hibernate:
        type:
          descriptor:
            sql: trace

